###
### Warming: Keep this file out of version control in Production environment
###


### The parent directory for profiles.yml is determined using the following precedence:
### 1) --profiles-dir option
### 2) DBT_PROFILES_DIR environment variable
### 3) current working directory
### 4) ~/.dbt/ directory


# Note: Create local db "dbt_test_db" and local schema "dbt_local_schema"
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: dbt_test_db
      schema: dbt_local_schema
      threads: 4